### ISSUE TITLE
Unmodified files are added with CommitCommand.setAll(true) 

### ISSUE THREAD

**Issue by insert0** [eclipse-jgit/jgit-website#1]
Hi,

I hope this is the home of eclipse JGit library :-)

We are using JGit 6.3.0.202209071007-r (and tried with 6.6.0.202305301015-r as well), and the same behavior was observed. When we have         
`        CommitCommand commitCommand = git.commit()
                                         .setAll(true)
                                         .setAllowEmpty(false)
                                         .setMessage(title)
                                         .setCommitter(author, authorEmail)
                                         .setAuthor(author, authorEmail);`
it adds some unmodified files from the same repository as part of the commit. I couldn't figure out why such behavior happens. I tried to check diff prior to committing and it didn't show the unmodified file.

Current temp solution I am thinking is to use 
`commitCommand.setOnly(filename)` 
on the modified files only, then I was able to create a proper commit without the unmodified files included. 

So, I was wondering if there were known/reported issues around the same/similar matter? If not, can it be reviewed and address the issue?

Thank you for the great library and thank you for the support in advance.

Regards,
Dong-Jun

**Comment by msohn** [comment]
this is the repo for the jgit website, we still use bugzilla to track issues for jgit, see https://wiki.eclipse.org/EGit/Contributor_Guide#Bugs
