### ISSUE TITLE
Upgradation to jakarta package in org.eclipse.jgit 

### ISSUE THREAD

**Issue by kvaishnavi97** [eclipse-jgit/jgit-website#2]
Hello,

I am using the latest version of org.eclipse.jgit (6.7.0.202309050840-r). I have upgraded my existing project to Spring Boot 3 and Java 17.
As we know, the Javax package has been moved to Jakarta.
I am using the Gitservlet class belonging to package `org.eclipse.jgit.http.server`.
This class is using some properties of HttpServelt, but HttpServlet has been moved to Jakarta.
Hence, after adding dependencies, I am getting a compilation error, as mentioned in the below screenshot.

Are you planning to fix this in the next version?

![image](https://github.com/eclipse-jgit/jgit-website/assets/53962056/c3ce577b-ec81-4d2a-b8af-af0904bb262b)

**Comment by msohn** [comment]
this is the repo for the jgit website
we still use Bugzilla for bug tracking, see https://wiki.eclipse.org/EGit/Contributor_Guide#Bugs
